spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: Admin.12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8741/eureka/
